CREATE table people(
    people_id INT PRIMARY KEY generated by default as identity ,
    fullName varchar unique not null ,
    yearOfBirth int CHECK ( yearOfBirth>1900 ) not null
);
create table book(
    book_id INT primary key generated by default as identity ,
    title varchar not null ,
    author varchar not null ,
    publishYear int not null ,
    people_id int references people(people_id)
);